# POST http://localhost:3001/api/login
# Content-Type: application/json

# {
#     "username":"Dsa",
#     "password":"salainen"
# }


# POST http://localhost:3001/api/users
# Content-Type: application/json

# {
#     "username":"Dsa",
#     "name":"computer scientist",
#     "password":"salainen"
    
# }

DELETE http://localhost:3001/api/root

